workspace = { members = ["strava"] }
[package]
name = "strava-analysis"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strava = { path = "./strava" }
chrono = "0.4.31"
